markdown: kramdown
url: "https://thestuffihave.online"
plugins:
  - jekyll-sitemap
exclude:
  - tests
  - porpoise-api
  - "Porpoise AI"
  - porpoise/verify-site.py
  - porpoise/verify-integration.py
